### ISSUE TITLE
Support for Wally?

### ISSUE THREAD

**Issue by u-train** [sircfenner/StudioComponents#1]
Hey! I have been eyeing this project to use for my new plugin. However, I've also been planning to use Wally, the package manager. So, can there be support for Wally?

**Comment by sircfenner** [comment]
Sorry for the delay getting back to you on this. Definitely open to that - feel free to PR in any relevant changes including the fix to Background I see in your fork.

**Comment by u-train** [comment]
Hey, no worries about the delay. You responded which matters!

Here's [the PR for the background](https://github.com/sircfenner/StudioComponents/pull/3).

In terms of Wally, you'd have to set that up so that you can publish it to the registry. The first step would be grabbing the CLI tool [here](https://wally.run/install). Run `wally init` when done. Then go into the `wally.toml` file and Roact as a dependency.
```diff
+ [dependencies]
+ Roact = "roblox/roact@1.4.2"
```
Run Wally install. Note the new `Packages` folder. Make sure to have it listed in `.gitignore`. Delete the `Vendor` folder along with the submodule for Roact itself. Go into the `project.develop.json` and set the path for `Vendor` to the new `Package` folder. Then, you're off to publishing it. Run `wally publish`.

Now, on my fork, I did go ahead and replace all instances of `Vendor` with `Packages`. But, it isn't needed.

**Comment by sircfenner** [comment]
Added in https://github.com/sircfenner/StudioComponents/pull/4
