### ISSUE TITLE
Export BaseButton & Constants

### ISSUE THREAD

**Issue by sircfenner** [sircfenner/StudioComponents#33]
BaseButton's intended purpose is for creating custom-styled buttons with built-in hover/press/select/disabled behavior. It should be exported so it can be used for this.

Constants now contain values that library consumers need to access, such as CheckboxIndeterminate. In future this should probably be split out from the internal constants such as ZIndex.

**Comment by u-train** [comment]
- Ought to consider using an (enumeration library like howmanysmall's)[https://github.com/howmanysmall/enumerator/] for stuff like Checkbox.
- #15 did a good job showing how to hoist constants into props.

**Comment by sircfenner** [comment]
I'd like to avoid introducing anything other than plain data into props wherever possible.

As for exposing these values, I don't think the approach from that PR helps us here. There are two categories of constant that we care about:
1. Values that are shared between different components, such as default Font and TextSize
2. Values which hold specific meaning when supplied as props, where access is required both by components and by library consumers, such as Splitter orientation

By their nature, neither category of constant can be held internally by components. The issue is mostly about the best way to organize and expose them. For now I think it's acceptable for them to live in the same place so that library consumers can access what they need to.
