### ISSUE TITLE
Fusion Version

### ISSUE THREAD

**Issue by gamma-sigma-beep** [sircfenner/StudioComponents#42]
Right now there is only for Roact, which some people would not use over Fusion

Any ideas for Fusion version (I am not asking to replace roact with fusion, I'm asking for alternative version for fusion users)

**Comment by sircfenner** [comment]
Check out https://github.com/mvyasu/PluginEssentials#studiocomponents which includes a port of this project for Fusion

**Comment by gamma-sigma-beep** [comment]
> Check out https://github.com/mvyasu/PluginEssentials#studiocomponents which includes a port of this project for Fusion

had no idea that existed in the first place, Thanks!
