### ISSUE TITLE
Migration from roact to react-lua

### ISSUE THREAD

**Issue by RyanLua** [sircfenner/StudioComponents#43]
Roblox very recently just killed [roact](https://github.com/Roblox/roact) in favor of [react-lua](https://github.com/Roblox/react-lua). 

As it stands now there are some API changes and the documentation is a bit lacking but will we see StudioComponents moving?

**Comment by sircfenner** [comment]
I have a React version mostly ready including better documentation. This repository will most likely be archived and a new one will be made for the React version.

**Comment by Name-hw** [comment]
Where is that repository?

**Comment by sircfenner** [comment]
As of v1.0.0, this repo is hosting the react-lua migration
