### ISSUE TITLE
Add support for children on components

### ISSUE THREAD

**Issue by alreadypro** [sircfenner/StudioComponents#5]
Currently, it is impossible to add a child (in my case, UIStroke) to a Slider component. I know that the Label component currently supports this, and there are probably a few others that do as well. All components should support this in respect to any case where a component may require a child for functional or stylistic reasoning

**Comment by sircfenner** [comment]
I can see the use in being able to pass arbitrary children to components and am happy to get this added in. I think it does raise a couple of questions:
1. Where should the children be parented? It may not always be intended/sufficient to parent arbitrary children to the top-level/root instance, for example if you wanted to style the handle of a slider.
2. More fundamentally, should this library aim to allow customization/styling, given that it is aimed at facilitating a consistent user interface across plugins? If so, how should that work? Probably a wider discussion to be had here which would be more suitable as a separate issue.

**Comment by sircfenner** [comment]
Closing this in favour of individual issues per-component with specific use cases
